##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 3: Your Network as Code
# Author: Hank Preston <hapresto@cisco.com>
#
# Illustrate the following concepts:
# -
##############################################################
---
- name: Enable Features
  tags: [api, nxapi, vpc, vlan, trunks]
  loop:
    - vpc
    - lacp
  nxos_feature:
    feature: "{{ item }}"
    state: enabled

- name: Create Port Channels for Access Switches
  tags: [api, nxapi, vpc, vlan, trunks]
  loop: "{{ trunks }}"
  nxos_lag_interfaces:
    config: 
      - name: "port-channel{{ item.port_channel_id }}"
        members: 
          - member: "{{ item.members.0 }}"
            mode: active

- name: Make Port Channel Layer 2
  tags: [api, nxapi, vpc]
  loop: "{{ trunks }}"
  nxos_interfaces:
    config: 
      - name: "port-channel{{ item.port_channel_id }}"
        enabled: true 
        mode: layer2 

# BUG: The nxos_l2_interfaces module should be able to configure 
#  an interface as a trunk. However testing showed it isn't working 
#  in the current version of Ansible. Therefore the nxos_config module 
#  is used here to configure correctly.
- name: Configure Port Channel Trunk
  tags: [api, nxapi, vpc]
  loop: "{{ trunks }}"
  nxos_config: 
    lines: 
      - switchport mode trunk 
    parents: interface port-channel{{ item.port_channel_id }}

- name: Configure VPC for Trunks
  tags: [api, nxapi, vpc, vlan, trunks]
  loop: "{{ trunks }}"
  nxos_vpc_interface:
    portchannel: "{{ item.port_channel_id }}"
    vpc: "{{ item.port_channel_id }}"
