##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 2: Using Ansible for Network Configuration
# Author: Hank Preston <hapresto@cisco.com>
# 
# example1.yaml
# Illustrate the following concepts:
# - Basic Playbook Structure for NX-OS Modules
##############################################################
---
- name: Retrieve facts from Switches
  hosts: switches
  gather_facts: False

  # Ansible added new connection options for networking devices
  # to replace connection: local
  # Now connection: network_cli or httpapi are recommended
  #   Doc: https://docs.ansible.com/ansible/2.9/network/user_guide/platform_nxos.html 
  connection: network_cli
  
  tasks: 
    - name: "Retrieving NX-OS Facts"
      nxos_facts: 
        # See docs for what subset options of facts are available
        #   https://docs.ansible.com/ansible/2.9/modules/nxos_facts_module.html#nxos-facts-module 
        gather_subset: all
      register: nxos_info

    - name: "Print NX-OS Facts"
      debug: msg="{{nxos_info}}"
