##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 2: Using Ansible for Network Configuration
# Author: Hank Preston <hapresto@cisco.com>
# 
# example2.yaml
# Illustrate the following concepts:
# - Configuring NX-OS network interfaces with Ansible
##############################################################
---
- name: Configure Loopback Networks on Each Switch
  hosts: switches
  gather_facts: False

  # Ansible added new connection options for networking devices
  # to replace connection: local
  # Now connection: network_cli or httpapi are recommended
  #   Doc: https://docs.ansible.com/ansible/2.9/network/user_guide/platform_nxos.html 
  connection: network_cli
  
  tasks: 
    - name: Create Loopback Interface
      # Note: The "with_items" syntax has been replaced by "loop" 
      #  - https://docs.ansible.com/ansible/2.9/user_guide/playbooks_loops.html#with-items
      loop: "{{ local_loopbacks }}"
      # with_items: "{{ l3_fabric.interfaces }}"
      # Note: the nxos_interface module has been replaced with nxos_interfaces 
      #  and will be deprecated/removed soon. However the new nxos_interfaces 
      #  module has a bug in Ansible 2.9 when trying to create loopbacks. Keeping 
      #  this example using nxos_interface for now. 
      # Info: 
      #  - https://docs.ansible.com/ansible/2.9/modules/nxos_interfaces_module.html
      #  - https://docs.ansible.com/ansible/2.9/modules/nxos_interface_module.html
      nxos_interface: 
        interface: "{{ item.name }}"
        mode: layer3
        description: "{{ item.desc }}"



    # Note: The module nxos_ip_interface was obsoleted by Ansible and replaced with 
    #  nxos_l3_interfaces. This module provides the same purpose, but with different 
    #  syntax. See details at: 
    #  - https://docs.ansible.com/ansible/2.9/modules/nxos_l3_interfaces_module.html
    - name: Configure IPv4 Address on Interface
      # Note: The "with_items" syntax has been replaced by "loop" 
      #  - https://docs.ansible.com/ansible/2.9/user_guide/playbooks_loops.html#with-items
      loop: "{{ local_loopbacks }}"
      # Note: to stay consistent with the videos for the lesson, this playbook 
      #  uses the loop construct for configuring interfaces. The current module 
      #  does support multiple interfaces in one task execution, and that would 
      #  be a more efficient configuration.
      nxos_l3_interfaces:
        state: merged
        config: 
          - name: "{{ item.name }}"
            ipv4: 
              - address: "{{ item.ip_address }}/{{ item.prefix }}"
