##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 3: Your Network as Code
# Author: Hank Preston <hapresto@cisco.com>
#
# Illustrate the following concepts:
# -
##############################################################
---
- name: Enable Features
  tags: [api, nxapi, layer3]
  loop:
    - interface-vlan
  nxos_feature:
    feature: "{{ item }}"
    state: enabled

- name: Configure Layer 3 Interfaces
  tags: [api, nxapi, layer3]
  loop: "{{ l3_interfaces }}"
  # Note: the nxos_interface module has been replaced with nxos_interfaces 
  #  and will be deprecated/removed soon. However the new nxos_interfaces 
  #  module has a bug in Ansible 2.9 when trying to create loopbacks or SVI. 
  #  Keeping this example using nxos_interface for now. 
  # Info: 
  #  - https://docs.ansible.com/ansible/2.9/modules/nxos_interfaces_module.html
  #  - https://docs.ansible.com/ansible/2.9/modules/nxos_interface_module.html
  nxos_interface:
    interface: "{{ item.interface_type }}{{ item.interface_id }}"
    mode: layer3
    description: "{{ item.description }}"
    admin_state: up

- name: Configure IPv4 Address on Interface
  tags: [api, nxapi, layer3]
  loop: "{{ l3_interfaces }}"
  nxos_l3_interfaces:
    config: 
      - name: "{{ item.interface_type }}{{ item.interface_id }}"
        ipv4: 
          - address: "{{ item.ip_address }}/{{ item.prefix }}"
