##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 3: Your Network as Code
# Author: Hank Preston <hapresto@cisco.com>
#
# Illustrate the following concepts:
# -
# 
# Note: This file has been updated to leverage the network_cli 
#  connection method. This is an update from the original 
#  version which is used in videos.
##############################################################
---
- name: Configure NETCONF
  tags: [api, netconf]
  ios_config:
    lines:
      # Note: Due to problem with older IOS XE Self Signed certs expiring 
      #  on Jan 1, 2020, manually changing time on routers to allow certs 
      #  to remain valid. 
      # Info: https://www.cisco.com/c/en/us/support/docs/security-vpn/public-key-infrastructure-pki/215118-ios-self-signed-certificate-expiration-o.html#anc9
      # This is only needed because Sandbox used has IOS XE 16.8.1a deployed.
      # newer CSR images would NOT need this fix. 
      - do clock set 10:00:00 1 Dec 2019
      - netconf-yang
      - netconf-yang cisco-odm polling-enable
      # - restconf
      # - ip http server
      # - ip http secure-server

- name: Pause for NETCONF to start
  pause:
    seconds: 45
