##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 3: Your Network as Code
# Author: Hank Preston <hapresto@cisco.com>
#
# Illustrate the following concepts:
# -
##############################################################
---
# - name: Configure VLANs
#   tags: [api, nxapi, vlan]
#   loop: "{{ vlans }}"
#   nxos_vlan:
#     vlan_id: "{{ item.id }}"
#     name: "{{ item.name }}"

- name: Configure VLANs
  tags: [api, nxapi, vlan]
  # Note: to stay consistent with the videos for the lesson, this playbook 
  #  uses the loop construct for configuring interfaces. The current module 
  #  does support multiple interfaces in one task execution, and that would 
  #  be a more efficient configuration.
  loop: "{{ vlans }}"
  # Note: the module nxos_vlan has been replaced with nxos_vlans in 
  #  recent versions of Ansible.
  nxos_vlans:
    config: 
      - vlan_id: "{{ item.id }}"
        name: "{{ item.name }}"

